//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FId { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Feedback1 { get; set; }
        public int PId { get; set; }
    }
}
